### ISSUE TITLE
Failure in setting  up plugin with neovim

### ISSUE THREAD

**Issue by kiran233588** [ckipp01/nvim-jenkinsfile-linter#3]
Using Linux Ubuntu Xenial
Installed Dependencies:  neovim (NVIM 0.6.1), curl
cat $HOME/.config/nvim/init.vim
```
...
call plug#begin()
Plug 'https://github.com/preservim/nerdtree'
Plug 'http://github.com/ckipp01/nvim-jenkinsfile-linter'
Plug 'http://github.com/nvim-lua/plenary.nvim'
...
set encoding=UTF-8
call plug#end()
```
Able to install Plugins in nvim using `PlugInstall` command

I set the environment variables 
```
export JENKINS_USERNAME=<username>
export JENKINS_HOST=<jenkin host>
export JENKINS_PASSWORD=<pasword>
```

However when I try to use in nvim to edit Jenkinfile. Its not autosuggesting anything.
Any help on this would be very useful

**Comment by ckipp01** [comment]
Hey @kiran233588, nvim-jenkinsfile-linter is only that, a linter. It won't give you code completions or suggestions or anything like that. The only functionality it has is the validate function https://github.com/ckipp01/nvim-jenkinsfile-linter/blob/dcb3fa8025992921f8f23dd612c3ab77db4b71e0/doc/jenkinsfile-linter.txt#L45.

Have you tried mapping this and trying it?

**Comment by kiran233588** [comment]
> Hey @kiran233588, nvim-jenkinsfile-linter is only that, a linter. It won't give you code completions or suggestions or anything like that. The only functionality it has is the validate function
> 
> https://github.com/ckipp01/nvim-jenkinsfile-linter/blob/dcb3fa8025992921f8f23dd612c3ab77db4b71e0/doc/jenkinsfile-linter.txt#L45
> 
> .
> Have you tried mapping this and trying it?
new to neovim where to put this code!

**Comment by ckipp01** [comment]
Did you mean to include a reply?

**Comment by kiran233588** [comment]
How you validate the Jenkinsfile ?

**Comment by ckipp01** [comment]
As the docs mention you need to create a mapping that calls the validate function. For example I have

```lua
nvim.api.nvim_set_keymap("n", "<leader><leader>j", [[<cmd>lua require("jenkinsfile_linter").validate()<CR>]])
```
Which allows me to use `<leader><leader>j` to validate the file.

**Comment by ckipp01** [comment]
I believe you have everything you need. If not, feel free to report back.

**Comment by zekena2** [comment]
Hi 
I get this error when I enter this command `lua require("jenkinsfile_linter").validate()` 
`Error executing vim.schedule lua callback: Vim:E474: Unidentified byte: Moved Permanently`

**Comment by ckipp01** [comment]
Hi @zekena2, are you triggering it manually? In a mapping? What version of Neovim are you using?

**Comment by zekena2** [comment]
neovim version: `NVIM v0.6.0-dev+43-g02bf251bb`
I'm triggering it manually.

**Comment by ckipp01** [comment]
> neovim version: `NVIM v0.6.0-dev+43-g02bf251bb` I'm triggering it manually.
> 
> Edit: I've vim plug and installed the required plguin `nvim-lua/plenary.nvim` but tbh don't know how it works.

All you need to do is have it installed and then `nvim-jenkisnfile-linter` just uses it as a library of sorts. Honestly I've never seen that error message before and am unsure how to help. Can you provide a minimal configuration where this is happening for you?

**Comment by bayram-dev** [comment]
Hello, @ckipp01 
Also issueing such problem whenever i try to validate config. I'll open new issue, cuz it doesn't interfier basic setups of jenkins.
